#include "test.h"
#include "palette.h"

void test_palette(void) {
    for (int i = 0; i < COL_COUNT; i++) CHECK_EQ(PALETTE_NIGHT[i].a, 255);
    CHECK(PALETTE_NIGHT[COL_SKY_TOP].r < 20 && PALETTE_NIGHT[COL_SKY_TOP].g < 20 && PALETTE_NIGHT[COL_SKY_TOP].b < 20);
    CHECK(PALETTE_NIGHT[COL_FOOTPRINT].r > 180 && PALETTE_NIGHT[COL_FOOTPRINT].g > 55 && PALETTE_NIGHT[COL_FOOTPRINT].g < 130 && PALETTE_NIGHT[COL_FOOTPRINT].b < 80);
    CHECK(PALETTE_NIGHT[COL_HAMMER].r > PALETTE_NIGHT[COL_HAMMER].g && PALETTE_NIGHT[COL_HAMMER].g > PALETTE_NIGHT[COL_HAMMER].b);
    CHECK(PALETTE_NIGHT[COL_BRICK].r > PALETTE_NIGHT[COL_BRICK].g);
    CHECK(PALETTE_NIGHT[COL_ASPHALT].r < 80);
    CHECK(COL_COUNT >= 30);
}
