#ifndef PALETTE_H_HEADER
#define PALETTE_H_HEADER
#include "draw.h"

enum {
    COL_BG = 0, COL_SKY_TOP, COL_SKY_BOTTOM, COL_STAR, COL_TOWER, COL_TOWER_WINDOW,
    COL_BRICK, COL_BRICK_DARK, COL_MORTAR, COL_CONCRETE, COL_CONCRETE_DARK, COL_GRIME,
    COL_WINDOW_LIT, COL_WINDOW_LIT2, COL_WINDOW_DARK, COL_NEON, COL_NEON_GLOW, COL_SIGN,
    COL_POSTER, COL_POSTER_INK, COL_DUMPSTER, COL_DUMPSTER_DARK,
    COL_ASPHALT, COL_ASPHALT_DARK, COL_PUDDLE, COL_PUDDLE_LIGHT,
    COL_FOOTPRINT, COL_FOOTPRINT_DIM, COL_LAMP, COL_LAMP_LIGHT,
    COL_DOG, COL_DOG_DARK, COL_TRASH, COL_TRASH_DARK, COL_PAPER,
    COL_BUG, COL_BUG_DARK, COL_DUST, COL_HAND, COL_HAMMER, COL_HANDLE, COL_TEXT,
    COL_COUNT
};

extern const Color PALETTE_NIGHT[COL_COUNT];

#endif
