#ifndef PALETTE_H
#define PALETTE_H
#include "draw.h"

enum {
    COL_BG = 0, COL_GRID, COL_HORIZON, COL_FLOOR,
    COL_BUG_A, COL_BUG_B, COL_BUG_C, COL_BUG_DARK,
    COL_HERO_BODY, COL_HERO_SKIN, COL_HAMMER, COL_HANDLE, COL_HAT,
    COL_TEXT, COL_RED, COL_GREEN, COL_DUST, COL_PROP, COL_PROP_DARK, COL_GLOW,
    COL_COUNT
};

extern const Color PALETTE_BUGS[COL_COUNT];

#endif
